spring:
  application:
    name: service-config



  cloud:
    config:
      server:
        git:
          uri: https://github.com/TIME69/springboot-study/
          search-paths:
          username:
          password:
      label: master
      profile: dev

server:
  port: 8888
